### ISSUE TITLE
error 500 with snmpgeneric.php

### ISSUE THREAD

**Issue by lucasevabou14** [github138/myRT-contribs#3]
Mon Jul 03 11:10:27 2017] [error] [client 172.16.12.80] PHP Parse error:  syntax error, unexpected '[' in /var/www/racktables/plugins/2/snmpgeneric.php on line 95

racktables 0.20.11
php 5.3.3

**Comment by github138** [comment]
PHP Version? Needs PHP >= 5.4

**Comment by lucasevabou14** [comment]
Yes Updated to PHP 7 but now I have following error when I click on show list :+1: 
PHP Fatal error:  Uncaught Error: Call to undefined function renderTableViewer()

**Comment by github138** [comment]
This function comes with Racktables 0.20.12

You could try the old snmpgeneric.php with older Racktables  versions:
https://github.com/github138/myRT-contribs/blob/snmpgeneric-v0.0/snmpgeneric.php

**Comment by lucasevabou14** [comment]
Ok found thanks
