### ISSUE TITLE
Internal error when polling Dell S4820

### ISSUE THREAD

**Issue by jpobeda** [github138/myRT-contribs#4]
Hi there,

I tried to poll a Force10 S4820T stacked switch and I got this error

> Internal error
> 
> 
> Argument 'ip' of value '36.5.148.0.0.1.0.1.0.0.0.0.0.0.0.1' is invalid (Invalid IP address).

It is something related to the fact that are stacked switches? The error is not related to dns resolution because I get the same by entering the IP instead of dns name.

 If it is of any help, I ran the Racktables SNMPSync and it's got the ports for 1 switch.

This is the snmpwalk

.1.3.6.1.2.1.1.1.0 = STRING: Dell Networking OS
Operating System Version: 2.0
Application Software Version: 9.7(0.0)
Series: S4820T
Copyright (c) 1999-2015 by Dell Inc. All Rights Reserved.
Build Time: Fri Feb 27 06:45:43 2015
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.6027.1.3.17
.1.3.6.1.2.1.1.3.0 = 2817457248
.1.3.6.1.2.1.1.4.0 = STRING: xxxxxxx admin
.1.3.6.1.2.1.1.5.0 = STRING: xxxxxxr0
.1.3.6.1.2.1.1.6.0 = STRING: XXX, YYYYYYYY
.1.3.6.1.2.1.1.7.0 = INTEGER: 6

Let me know if you need any further details.

Running RT 0.20.13 and snmpgeneric.php from https://github.com/github138/myRT-contribs/tree/develop-0.20.x

**Comment by github138** [comment]
Hi Javier,

could you provide an snmpwalk of these tables please: (remove sensitive 
data)

ipAddrTable             1.3.6.1.2.1.4.20
ipAddressTable  1.3.6.1.2.1.4.34
ipv6AddrAddress 1.3.6.1.2.1.55.1.8

**Comment by jpobeda** [comment]
Hi Maik,

Let me know if you need further details.

[dells4820_1.zip](https://github.com/github138/myRT-contribs/files/1123046/dells4820_1.zip)

**Comment by github138** [comment]
Hi Javier,

thanks for that.

Could you also provide the ipAddressPrefixTable 1.3.6.1.2.1.4.32 snmpwalk of that device?

**Comment by jpobeda** [comment]
Hi Maik,

There you go.

[dells4820.4.log.zip](https://github.com/github138/myRT-contribs/files/1126016/dells4820.4.log.zip)

**Comment by github138** [comment]
Hi Javier,

i have made some changes in the new "ipv6" branch:
https://github.com/github138/myRT-contribs/blob/ipv6/snmpgeneric.php

Please let me know if this works.

Regards,
Maik

**Comment by jpobeda** [comment]
It worked like a charm!

**Comment by jpobeda** [comment]
There is an small issue I didn't realise before.

Almost every port came up with the same MAC address and when I populated the first member of the stack I went well but when I tried the second member I've got this error:

Argument 'L2 address' of value '90B11CF45B52' is invalid (already used by object#255 port 'ma0/0').

I also tried to unmark the "upd mac" field with the same result.

Every port on the first member have got this MAC address but error is only complaining about ma0/0.

This is an stacked switch, so I basically have 2 devices, for hardware inventory purposes and the "network chassis" as a container for these two.

**Comment by github138** [comment]
Hi Javier,

Racktables does not allow to create two ports with the same "L2 address".

Are these ports pyhsical or virtual?

Can you provide a complete snmpwalk of the interfaces table (oid: 
1.3.6.1.2.1.2 )?

Thanks,
Maik

**Comment by jpobeda** [comment]
Hi Maik,

Yes, I know it should be allowed by RT but snmpgeneric did it.

Look at the screenshot and You'll see that every port was created with the same MAC. I know it shouldn't have happened but... 

I also thought that unmarking the "upd mac" field would not care about the MACs and not update them, like creating the ports with empty MACs.

![rt_issue 4_1](https://user-images.githubusercontent.com/13456559/27997530-b9840b98-654d-11e7-803c-9a846c40feba.png)

I attached snmpwalk as well and I can see that all of them have got that exactly same MAC...odd isn't it?

[dells4820.5.log.zip](https://github.com/github138/myRT-contribs/files/1134064/dells4820.5.log.zip)

**Comment by github138** [comment]
Hi Javier,

do you get the same MAC addresses via the CLI of the Switch or only via 
SNMP?
Regards,
Maik

**Comment by jpobeda** [comment]
Hi Maik,

Don't ask my why, the switch also shows the same MAC for every port via CLI. So I'd say both, from CLI and from SNMP. 

Unlike Cisco it looks like Dell allocates a unique MAC to every physical port?

I've check 3 of these switches and are all the same.

I've never understood what's the purpose of populating the Physical MAC of a port instead of the dynamic MAC from the device connected to it... I can't see any good reason to have that. Can you give any useful example for this?

**Comment by github138** [comment]
Hi Javier,

i just commited an update to the plugin with duplicate l2 address handling.
Duplicate addresses are removed.

Could you test this and let me know if this works?

Thanks,
Maik

**Comment by jpobeda** [comment]
Hi Maik,

I tested it and I get this:

> Internal error
> 
> 
> Argument 'ip' of value '36.5.148.0.0.1.0.1.0.0.0.0.0.0.0.1' is invalid (Invalid IP address).

It seems like same issue from first update has been re introduced. Let me know if you any other snmpwalk to sort this out.

**Comment by github138** [comment]
Hi Javier,

sorry forget to include ipv6 branche.
Done now so please try again with the newest version.
Thanks
Maik

**Comment by jpobeda** [comment]
It worked!

Shall we close this issue?

Thanks!

**Comment by github138** [comment]
If it is solved. Please close it.
Thanks,
Maik
